### ISSUE TITLE
Script fails with `ModuleNotFoundError: No module named 'mysql'`

### ISSUE THREAD

**Issue by dale-c-anderson** [GoogleCloudPlatform/aws-to-stratozone-export#17]
In a new cloud shell with a fresh clone from today, the script fails right off the bat:

```
[cloudshell-user@ip-10-0-84-12 ~]$ git clone https://github.com/GoogleCloudPlatform/aws-to-stratozone-export.git
Cloning into 'aws-to-stratozone-export'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 140 (delta 78), reused 89 (delta 38), pack-reused 0
Receiving objects: 100% (140/140), 106.40 KiB | 3.55 MiB/s, done.
Resolving deltas: 100% (78/78), done.

[cloudshell-user@ip-10-0-84-12 ~]$ cd aws-to-stratozone-export/

[cloudshell-user@ip-10-0-84-12 aws-to-stratozone-export]$ python3 stratozone-aws-export.py
Traceback (most recent call last):
  File "stratozone-aws-export.py", line 34, in <module>
    from db.rds_scanner import RdsScanner
  File "/home/cloudshell-user/aws-to-stratozone-export/db/rds_scanner.py", line 25, in <module>
    from db.mysql_scanner import MysqlScanner
  File "/home/cloudshell-user/aws-to-stratozone-export/db/mysql_scanner.py", line 20, in <module>
    import mysql.connector
ModuleNotFoundError: No module named 'mysql'
```

**Comment by dale-c-anderson** [comment]
`$ uname -a` from the shell:
```
Linux ip-10-0-84-12.ca-central-1.compute.internal 4.14.301-224.520.amzn2.x86_64 #1 SMP Fri Dec 9 09:57:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pnancarrow** [comment]
I'm experiencing this same issue. I was attempting to run locally rather than in cloud shell. also note that I ran `python3 stratozone-aws-export.py --no_perf` which I would expect doesn't need mysql based on the README.

**Comment by DmytroKerez** [comment]
Got the same issue.

**Comment by pnancarrow** [comment]
install dependencies with `python3 -m pip install -r requirements.txt` before running the script

**Comment by vksampath** [comment]
Thank you for the feedback.  The instructions are now updated to include this as one of the steps.
